// Code generated by "gen -pkg ."; DO NOT EDIT.

package record

import (
	"golang.org/x/net/context"
	"ndp/lib/trace"
)

func AddRecord(ctx context.Context, caller, callee string) error {
	ctx = trace.WithLables(ctx, "ndp/n3d/wxapp/record.AddRecord")
	return addRecord(ctx, caller, callee)
}

func GetRecordList(ctx context.Context, caller string) ([]RecordList, error) {
	ctx = trace.WithLables(ctx, "ndp/n3d/wxapp/record.GetRecordList")
	return getRecordList(ctx, caller)
}

func DeleteRecord(ctx context.Context, id int) error {
	ctx = trace.WithLables(ctx, "ndp/n3d/wxapp/record.DeleteRecord")
	return deleteRecord(ctx, id)
}
